baseURL = 'https://troglodytto.github.io/'
languageCode = 'en-us'
title = "Piyush Upadhyay's Blog"
theme = "shibui"


[menu]
    [[menu.main]]
        name = "Zeno"
        pageRef = "/posts/zeno"
        weight = 1
        identifier = "zeno"
        [menu.main.params]
          subtitle = "Writing an OS kernel in Rust"
          # draft = true
          # hidden = true

    [[menu.main]]
        name = "Hyperion"
        pageRef = "/posts/hyperion"
        weight = 40
        identifier = "hyperion"
        [menu.main.params]
          subtitle = "Implementing the HTTP protocol from scratch"
          draft = true
          hidden = true

    [[menu.main]]
        name = "Daiquiri"
        pageRef = "/posts/cluster-triage"
        weight = 10
        identifier = "cluster-triage"
        [menu.main.params]
        subtitle = "Untangling a broken production at 3AM"

    [[menu.main]]
        name = "Rust give you wings"
        pageRef = "/posts/rust-gives-you-wings"
        weight = 20
        identifier = "rust-gives-you-wings"
        [menu.main.params]
        subtitle = "Shameless propaganda for a compiler that argues back"

    [[menu.main]]
        name = "Agent workflow"
        pageRef = "/posts/agent-workflow"
        weight = 30
        identifier = "agent-workflow"
        [menu.main.params]
        subtitle = "Rebuilding an agent setup from zero"

    [[menu.main]]
        name = "Beliefs"
        pageRef = "/posts/beliefs"
        weight = 100
        identifier = "beliefs"
        [menu.main.params]
        subtitle = "Things I believe to be true"
        divider = true

    [[menu.main]]
        name = "How can I help?"
        pageRef = "/posts/how-can-i-help"
        weight = 110
        identifier = "how-can-i-help"
        [menu.main.params]
        subtitle = "Just an effort to bring a little light to the world"

    [[menu.main]]
        name = "Sunset"
        pageRef = "/posts/sunset"
        weight = 120
        identifier = "sunset"
        [menu.main.params]
        subtitle = "A séance for my own soul"

[markup]
    [markup.highlight]
        style = "rose-pine-dawn"
        lineNos = true
        lineNumbersInTable = false
        noClasses = true


[caches]
  [caches.images]
    dir = ':cacheDir/images'
